# Generated by Django 5.2.6 on 2025-10-15 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhe', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('endereco_completo', models.TextField(blank=True, verbose_name='Endereço Completo')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='jotanunes.ambiente')),
                ('descricoes', models.ManyToManyField(blank=True, related_name='itens', to='jotanunes.descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='jotanunes.item')),
                ('marcas', models.ManyToManyField(blank=True, related_name='materiais', to='jotanunes.marca')),
            ],
        ),
        migrations.AddField(
            model_name='ambiente',
            name='obra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='jotanunes.obra'),
        ),
        migrations.CreateModel(
            name='Torre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torres', to='jotanunes.obra')),
            ],
        ),
        migrations.AddField(
            model_name='ambiente',
            name='torre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='jotanunes.torre'),
        ),
    ]
