# Generated by Django 5.2.7 on 2025-10-31 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotanunes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Estado')),
                ('uf', models.CharField(max_length=2, unique=True, verbose_name='UF (Sigla)')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='obra',
            name='status',
            field=models.CharField(choices=[('RECUSADO', 'Recusado'), ('EM_ANALISE', 'Em Análise'), ('NAO_FINALIZADO', 'Não Finalizado'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=20),
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='jotanunes.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
            },
        ),
    ]
