# Generated by Django 5.2.7 on 2025-11-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotanunes', '0004_cidade_estado_delete_municipio_cidade_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='status',
            field=models.CharField(choices=[('RECUSADO', 'Recusado'), ('EM_ANALISE', 'Em Análise'), ('NAO_FINALIZADO', 'Não Finalizado'), ('FINALIZADO', 'Finalizado')], default='EM_ANALISE', max_length=20),
        ),
    ]
