# Generated by Django 5.2.7 on 2025-11-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotanunes', '0004_cidade_estado_delete_municipio_cidade_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['nome'], 'verbose_name': 'Cidade'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['nome'], 'verbose_name': 'Estado'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='ambiente',
        ),
        migrations.AddField(
            model_name='ambiente',
            name='itens',
            field=models.ManyToManyField(blank=True, related_name='ambientes', to='jotanunes.item'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='status',
            field=models.CharField(choices=[('RECUSADO', 'Recusado'), ('EM_ANALISE', 'Em Análise'), ('NAO_FINALIZADO', 'Não Finalizado'), ('FINALIZADO', 'Finalizado')], default='NAO_FINALIZADO', max_length=20),
        ),
    ]
