# Generated by Django 5.2.7 on 2025-11-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jotanunes', '0005_alter_cidade_options_alter_estado_options_and_more'),
        ('jotanunes', '0005_alter_obra_status'),
    ]

    operations = [
    ]
