# Generated by Django 5.2.7 on 2025-11-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotanunes', '0006_merge_20251105_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='descricao',
        ),
        migrations.AddField(
            model_name='obra',
            name='observacao',
            field=models.TextField(blank=True, null=True, verbose_name='Observação / Prefácio'),
        ),
    ]
