# Generated by Django 5.2.7 on 2025-11-26 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jotanunes', '0007_remove_obra_descricao_obra_observacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambiente',
            name='torre',
        ),
        migrations.DeleteModel(
            name='Torre',
        ),
    ]
