# Generated by Django 5.2.7 on 2025-11-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotanunes', '0008_remove_ambiente_torre_delete_torre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='observacao',
        ),
        migrations.AddField(
            model_name='obra',
            name='prefacio',
            field=models.TextField(blank=True, null=True, verbose_name='Prefácio'),
        ),
    ]
