# Generated by Django 5.2.7 on 2025-11-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotanunes', '0009_remove_obra_observacao_obra_prefacio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obra',
            name='prefacio',
        ),
        migrations.AddField(
            model_name='obra',
            name='texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
