# Generated by Django 5.2.7 on 2025-11-27 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jotanunes', '0010_remove_obra_prefacio_obra_texto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='texto',
            new_name='texto_prefacio',
        ),
    ]
