# Generated by Django 5.2.7 on 2025-11-29 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Descricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalhe', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True, verbose_name='Nome do Estado')),
                ('uf', models.CharField(max_length=2, unique=True, verbose_name='UF (Sigla)')),
            ],
            options={
                'verbose_name': 'Estado',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidades', to='jotanunes.estado', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricoes', models.ManyToManyField(blank=True, related_name='itens', to='jotanunes.descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='jotanunes.item')),
                ('marcas', models.ManyToManyField(blank=True, related_name='materiais', to='jotanunes.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('texto_prefacio', models.TextField(blank=True, null=True)),
                ('endereco_completo', models.TextField(blank=True, verbose_name='Endereço Completo')),
                ('observacao_final', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECUSADO', 'Recusado'), ('EM_ANALISE', 'Em Análise'), ('NAO_FINALIZADO', 'Não Finalizado'), ('FINALIZADO', 'Finalizado')], default='NAO_FINALIZADO', max_length=20)),
                ('cidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jotanunes.cidade')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jotanunes.estado')),
            ],
        ),
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('PRIVATIVO', 'Unidade Privativa'), ('COMUM', 'Área Comum')], max_length=20)),
                ('itens', models.ManyToManyField(blank=True, related_name='ambientes', to='jotanunes.item')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='jotanunes.obra')),
            ],
        ),
    ]
