# Generated by Django 5.2.7 on 2025-12-03 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotanunes', '0003_obra_materiais'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='observacao_gestor',
            field=models.TextField(blank=True, help_text='Observação privada do gestor.', null=True),
        ),
    ]
