# Generated by Django 5.2.7 on 2025-12-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotanunes', '0005_obra_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
