FROM node:20-alpine AS builder

ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}
WORKDIR /app
COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm ci

# Copia o resto do código do frontend
COPY ./frontend/ ./
RUN npm run build

FROM nginx:1.25-alpine

# Copia a configuração do Nginx
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Copia o build do front
COPY --from=builder /app/build /usr/share/nginx/html

EXPOSE 80