# Generated by Django 5.2.7 on 2025-12-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jotanunes', '0002_alter_ambiente_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='materiais',
            field=models.ManyToManyField(blank=True, related_name='obras', to='jotanunes.material'),
        ),
    ]
